### PR TITLE
Parse the image_id and push all tags corresponding to that image_id

### PR DESCRIPTION
**Pull request by torsava**
Previously we parsed the tags directly from the output.

This corresponds to the PR https://github.com/sclorg/container-common-scripts/pull/113.

### CODE REVIEW

**Comment by praiskup** [comment]
It is a bit magic, but if the `{{...}}` things work, OK.  This should be backward compatible with previous common-scripts.  Are you sure that all the image tags should be propagated?

**Comment by praiskup** [comment]
I mean, that _all_ the _local_ tags should be pushed to _remote_ registry?

**Comment by torsava** [comment]
@praiskup Hm, I thought that was what we discussed on the meeting. Do you know of any tags that we should not push?

On my system, I see the `raw` tag for it as well, which I'm not sure how it gets created, or if we want it there.

**Comment by praiskup** [comment]
I tried to build by buildah, and I see:
```
$ buildah images
...
localhost/centos/postgresql-10-centos7   1                  b3a2e5de3821   21 seconds ago   352 MB
localhost/centos/postgresql-10-centos7   latest             b3a2e5de3821   21 seconds ago   352 MB
localhost/centos/postgresql-10-centos7   20190404-88ba23b   b3a2e5de3821   21 seconds ago   352 MB
localhost/centos/postgresql-10-centos7   raw                b3a2e5de3821   21 seconds ago   352 MB
...
```
Is the dash in version OK, btw.?  I'd probably use `_`, but it is matter of taste.  Just asking to be sure.

Yes, I also think that `raw` and `squashed` should be omitted.

**Comment by praiskup** [comment]
```
case $image in
  *:raw|*:squashed) continue ;;
esac
```
?

**Comment by torsava** [comment]
> Is the dash in version OK, btw.? I'd probably use `_`, but it is matter of taste. Just asking to be sure.

Yes, underscores, periods and dashes are allowed. You like `_` better? I thought the dash would go better with the image name (`python-36-centos7`), etc. But if underscores are more common in tags, I can switch it.

**Comment by torsava** [comment]
> case $image in
>   *:raw|*:squashed) continue ;;
> esac

Sounds good, amended!

**Comment by praiskup** [comment]
This looks good to me, thanks!

**Comment by praiskup** [comment]
Ouch, sorry @torsava :-( this one was meant to be squashed, I noticed too late.

**Comment by praiskup** [comment]
deployed

**Comment by torsava** [comment]
> Ouch, sorry @torsava :-( this one was meant to be squashed, I noticed too late.

Yeah, there really should be some warning. Oh well, np.

> deployed

\o/ thanks! I'll update to new container-common-scripts in s2i-python-container on Monday and try it out. Don't want to debug production issues on a Friday :)

**Pull request merged**
