### PR TITLE
Allow testing images under OpenShift 4

### PR DESCRIPTION
**Pull request by phracek**
This commit allows checking containers under
OpenShift4 in each PR.
The pull request comment is [test-openshift-4]

I don't know if memcached should be updated too.
https://github.com/sclorg/rhscl-container-ci/compare/master...phracek:allow_trigger_ocp4?expand=1#diff-1b84b3d86cc46d0f493753302f9c32ed

The jenkins job should be generated together with https://github.com/sclorg/rhscl-container-ci/pull/37
Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

### CODE REVIEW

**Comment by phracek** [comment]
https://github.com/sclorg/rhscl-container-ci/pull/37

**Comment by hhorak** [comment]
I would personally not update devtoolset, llvm, and golang because we don't have any plans to have openshift-4 ready tests there any time soon, so it's not worth starting the job at all.

**Comment by hhorak** [comment]
> I don't know if memcached should be updated too.

Same as for the above, it's not worth adding el7 to memcached, same for openshift integration, which is not available in tests for memcached. So, I'd not touch this yaml at all as part of this PR.

**Comment by phracek** [comment]
@hhorak Thanks for the comments and great points. I have removed changes in devtoolset, lllvm, golang and memcached containers

**Comment by hhorak** [comment]
Cool, LGTM.

**Pull request merged**
